SELECT
  CAST(market_code AS STRING) AS market_code,
  CAST(market_code2 AS STRING) AS market_code2,
  CAST(market_code3 AS STRING) AS market_code3,
  CAST(team_id AS STRING) AS team_id,
  CAST(country_name AS STRING) AS country_name,
  CAST(NULL AS STRING) AS name,
  CAST(NULL AS STRING) AS batting_style,
  CAST(NULL AS STRING) AS id,
  CAST(NULL AS STRING) AS bowling_style,
  CAST(image_id AS STRING) AS image_id,
  CAST(file_name AS STRING) AS file_name,
  CAST(update_timestamp AS STRING) AS update_timestamp,
  CAST(NULL AS STRING) AS series_name,
  CAST(NULL AS STRING) AS match_id,
  CAST(NULL AS STRING) AS match_desc,
  CAST(NULL AS STRING) AS match_format,
  CAST(NULL AS STRING) AS match_status,
  CAST(NULL AS STRING) AS state,
  CAST(NULL AS STRING) AS team1_name,
  CAST(NULL AS STRING) AS team1_short,
  CAST(NULL AS STRING) AS team2_name,
  CAST(NULL AS STRING) AS team2_short,
  CAST(NULL AS STRING) AS venue_ground,
  CAST(NULL AS STRING) AS venue_city,
  CAST(NULL AS STRING) AS start_date,
  CAST(NULL AS STRING) AS end_date,
  CAST(NULL AS STRING) AS team1_runs,
  CAST(NULL AS STRING) AS team1_wickets,
  CAST(NULL AS STRING) AS team1_overs,
  CAST(NULL AS STRING) AS team2_runs,
  CAST(NULL AS STRING) AS team2_wicket,
  CAST(NULL AS STRING) AS team2_overs
FROM {{ ref('stg_gold_team_international') }}

UNION ALL

SELECT
  CAST(NULL AS STRING) AS market_code,
  CAST(NULL AS STRING) AS market_code2,
  CAST(NULL AS STRING) AS market_code3,
  CAST(id AS STRING) AS team_id,
  CAST(NULL AS STRING) AS country_name,
  CAST(name AS STRING) AS name,
  CAST(batting_style AS STRING) AS batting_style,
  CAST(id AS STRING) AS id,
  CAST(bowling_style AS STRING) AS bowling_style,
  CAST(image_id AS STRING) AS image_id,
  CAST(file_name AS STRING) AS file_name,
  CAST(update_timestamp AS STRING) AS update_timestamp,
  CAST(NULL AS STRING) AS series_name,
  CAST(NULL AS STRING) AS match_id,
  CAST(NULL AS STRING) AS match_desc,
  CAST(NULL AS STRING) AS match_format,
  CAST(NULL AS STRING) AS match_status,
  CAST(NULL AS STRING) AS state,
  CAST(NULL AS STRING) AS team1_name,
  CAST(NULL AS STRING) AS team1_short,
  CAST(NULL AS STRING) AS team2_name,
  CAST(NULL AS STRING) AS team2_short,
  CAST(NULL AS STRING) AS venue_ground,
  CAST(NULL AS STRING) AS venue_city,
  CAST(NULL AS STRING) AS start_date,
  CAST(NULL AS STRING) AS end_date,
  CAST(NULL AS STRING) AS team1_runs,
  CAST(NULL AS STRING) AS team1_wickets,
  CAST(NULL AS STRING) AS team1_overs,
  CAST(NULL AS STRING) AS team2_runs,
  CAST(NULL AS STRING) AS team2_wicket,
  CAST(NULL AS STRING) AS team2_overs
FROM {{ ref('stg_gold_team_players') }} 

UNION ALL

SELECT
  CAST(NULL AS STRING) AS market_code,
  CAST(NULL AS STRING) AS market_code2,
  CAST(NULL AS STRING) AS market_code3,
  CAST(NULL AS STRING) AS team_id,
  CAST(NULL AS STRING) AS country_name,
  CAST(NULL AS STRING) AS name,
  CAST(NULL AS STRING) AS batting_style,
  CAST(NULL AS STRING) AS id,
  CAST(NULL AS STRING) AS bowling_style,
  CAST(NULL AS STRING) AS image_id,
  CAST(file_name AS STRING) AS file_name,
  CAST(update_timestamp AS STRING) AS update_timestamp,
  CAST(series_name AS STRING) AS series_name,
  CAST(match_id AS STRING) AS match_id,
  CAST(match_desc AS STRING) AS match_desc,
  CAST(match_format AS STRING) AS match_format,
  CAST(match_status AS STRING) AS match_status,
  CAST(state AS STRING) AS state,
  CAST(team1_name AS STRING) AS team1_name,
  CAST(team1_short AS STRING) AS team1_short,
  CAST(team2_name AS STRING) AS team2_name,
  CAST(team2_short AS STRING) AS team2_short,
  CAST(venue_ground AS STRING) AS venue_ground,
  CAST(venue_city AS STRING) AS venue_city,
  CAST(start_date AS STRING) AS start_date,
  CAST(end_date AS STRING) AS end_date,
  CAST(team1_runs AS STRING) AS team1_runs,
  CAST(team1_wickets AS STRING) AS team1_wickets,
  CAST(team1_overs AS STRING) AS team1_overs,
  CAST(team2_runs AS STRING) AS team2_runs,
  CAST(team2_wicket AS STRING) AS team2_wicket,
  CAST(team2_overs AS STRING) AS team2_overs
FROM {{ ref('stg_gold_team_results') }} 